### PR TITLE
React 15.5 deprecation fix

### PR DESCRIPTION
**Pull request by szyablitsky**

### CODE REVIEW

**Comment by hustcc** [comment]
Does this can support React <15.5 ?

**Comment by szyablitsky** [comment]
Not sure, but may be adding 'prop-types' as peerDependency can help.

**Comment by szyablitsky** [comment]
https://github.com/brigade/react-waypoint/pull/172/files
Will fix to get back to less strict React version dependency.

**Comment by szyablitsky** [comment]
Now we support react 0.14 again

**Comment by hustcc** [comment]
Thank you very much, merge it.

I want to add travis-ci test for React component, then release the next version. Have you done something about React testing, maybe can help me.

**Comment by szyablitsky** [comment]
I will see if can help with this. I'm not an expert in JS testing.

**Comment by iKonrad** [comment]
Don't want to be a pain, but is there any chance for this to get merged soon?

**Comment by hustcc** [comment]
It has been merged, I will pubish new version today, sorry for waiting.

**Comment by hustcc** [comment]
@iKonrad done, v1.1.0 released.

**Pull request merged**
