### PR TITLE
add style prop to the rendered element

### PR DESCRIPTION
**Pull request by tommyku**
`style` props should be injected just like `className`.
Also allows other props being injected to the rendered `<time>` element.

### CODE REVIEW

**Comment by tommyku** [comment]
Am I supposed to bump the version in `package.json` too? 🤔

**Comment by hustcc** [comment]
You means you need the one new package version?

**Comment by hustcc** [comment]
I need to update the README, and then add demo in website, then publish the new version, can you help me do it ?

**Comment by tommyku** [comment]
What I really need is to have this merge show up on `npm`, but yeah I can submit another MR to 1) update README; 2) add demo; and 3) bump version number

**Comment by hustcc** [comment]
OK，Thank you.

**Pull request merged**
